
package com.example.demowsdltest.test1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SI_PURCHASE_OUTService", targetNamespace = "http://www.weaver.com/create_purchase_sender", wsdlLocation = "file:/D:/WSDL/wsdl.wsdl")
public class SIPURCHASEOUTService
    extends Service
{

    private final static URL SIPURCHASEOUTSERVICE_WSDL_LOCATION;
    private final static WebServiceException SIPURCHASEOUTSERVICE_EXCEPTION;
    private final static QName SIPURCHASEOUTSERVICE_QNAME = new QName("http://www.weaver.com/create_purchase_sender", "SI_PURCHASE_OUTService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/WSDL/wsdl.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SIPURCHASEOUTSERVICE_WSDL_LOCATION = url;
        SIPURCHASEOUTSERVICE_EXCEPTION = e;
    }

    public SIPURCHASEOUTService() {
        super(__getWsdlLocation(), SIPURCHASEOUTSERVICE_QNAME);
    }

    public SIPURCHASEOUTService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SIPURCHASEOUTSERVICE_QNAME, features);
    }

    public SIPURCHASEOUTService(URL wsdlLocation) {
        super(wsdlLocation, SIPURCHASEOUTSERVICE_QNAME);
    }

    public SIPURCHASEOUTService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SIPURCHASEOUTSERVICE_QNAME, features);
    }

    public SIPURCHASEOUTService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SIPURCHASEOUTService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SIPURCHASEOUT
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIPURCHASEOUT getHTTPPort() {
        return super.getPort(new QName("http://www.weaver.com/create_purchase_sender", "HTTP_Port"), SIPURCHASEOUT.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIPURCHASEOUT
     */
    @WebEndpoint(name = "HTTP_Port")
    public SIPURCHASEOUT getHTTPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.weaver.com/create_purchase_sender", "HTTP_Port"), SIPURCHASEOUT.class, features);
    }

    /**
     * 
     * @return
     *     returns SIPURCHASEOUT
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIPURCHASEOUT getHTTPSPort() {
        return super.getPort(new QName("http://www.weaver.com/create_purchase_sender", "HTTPS_Port"), SIPURCHASEOUT.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SIPURCHASEOUT
     */
    @WebEndpoint(name = "HTTPS_Port")
    public SIPURCHASEOUT getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.weaver.com/create_purchase_sender", "HTTPS_Port"), SIPURCHASEOUT.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SIPURCHASEOUTSERVICE_EXCEPTION!= null) {
            throw SIPURCHASEOUTSERVICE_EXCEPTION;
        }
        return SIPURCHASEOUTSERVICE_WSDL_LOCATION;
    }

}
